import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import { useState, useEffect } from 'react';
import {  faArrowUpFromBracket } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { useRef } from "react";
import { instance } from "../axios"
import { useRouter } from 'next/router';
export default function Home({ posts }) {
  const router = useRouter();
  useEffect(() => {

    if (localStorage.getItem("token")) {
      setLogged(true)
    }
  }, [])

  const [logged, setLogged] = useState(false);
  const [ image, setImage ] = useState("");
  const [ newpost, setNewpost ] = useState("");

  const ref = useRef();
  const onImageChange = (event) => {
    const files = event.target.files;
    setImage(files[0]);
  }
  const handleNewPostChange = (event) => {
    setNewpost(event.target.value);
  }

  const postSubmit = () =>{
    if(image && newpost){
      const data = new FormData();
      data.append('image', image);
      data.append('text', newpost);
      instance.post('/newpost', data)
      .then(res => {
          router.push('/')
      })
      .catch(err => {
          console.log(err)
          
      })
  setNewpost("");
  ref.current.value = "";
    }else{
      console.log("merci de remplir les champs")
    }
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className='container_home'>
        <div className='container_text_home'>
          <h1>Hugo Martin ♡</h1>
          <p className='text_home_p'>Hugo, tu es notre ami a tous, tu es un gameur, un bon vivant et un blagueur ! Hugo tu es aussi un chômeur !</p>
        </div>
      </div>
      {logged && <div className='container_create_post'>
        <h2>Nouveau post :</h2>
        <textarea maxLength="500" type="text" id="textarea_post" className="textarea_forum" onChange={handleNewPostChange} value={newpost}/>
        <div className="container_input_submit">
          <label className="label_upload" htmlFor="file_forum"><FontAwesomeIcon icon={faArrowUpFromBracket} className='icon_upload' /></label>
          <input type="file" id="file_forum" className="inputfileforum" name="image" ref={ref} onChange={onImageChange} />
          <button type="submit" className="btn_newpost_forum" onClick={postSubmit} >Post</button>
        </div>
      </div>}
      <div className='container_post_home'>
        {posts[0] ? posts.map(post => (

          <div key={post.id}>

            <div className='card_action_titre'>
              <p>{post.titre}</p>
            </div>


            <div className='container_img_action'>
              <div className='card_action_container_img'>
                <h2>{post.text}</h2>
                <Image alt="image d'un post" className='image_action' src={post.imageUrl} width={400} height={400} quality={100} />
                
              </div>
            </div>



          </div>

        ))

          : <p>pas de posts</p>}
      </div>

    </div>
  )
}


export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch("http://localhost:3001/api/post")
  const posts = await res.json()
  console.log(posts)
  //	const posts = []
  // Pass data to the page via props
  return { props: { posts } }
}